syntax on "语法高亮
set nocompatible "不与vi兼容
 
set number "显示行号 
"set nu “nu 为 number的缩写
 
"set relativenumber "显示相对行号
 
set cursorline "突出显示当前行  set cul
set cursorcolumn "突出显示当前列 set cuc
 
set showmatch "显示括号匹配
set showmode "在底部显示，当前处于命令模式还是插入模式
 
set bg=dark "设置黑色背景
:colorscheme desert
"设置缩进 1、设置TAB长度为4空格 2、设置自动缩进长度为4空格 3、继承前一行的缩进方式，适用于多行注释
set tabstop=4
set shiftwidth=4
set expandtab "按下tab自动转换为空格
autocmd BufWritePost $MYVIMRC source $MYVIMRC "实现.vimrc保存时自动重启加载
set wrap "设置自动换行 set nowarap 取消自动换行 
set showcmd "输入的命令显示出来，看的清楚些
 
"在命令模式下，按下tab可以自动补全命令
set wildmenu
set wildmode=longest,list,full
set backspace=indent,eol,start "inset模式下，使退格键可以删掉任何东西
 
set hlsearch "搜索高亮  
exec "nohlsearch"
set incsearch "高亮显示搜索的匹配过程，每输入一个字符，就自动跳转到第一个匹配结果
 
set ignorecase "
set smartcase  "  
set mouse=a    "
set autoindent "自动缩进，按下回车后，下一行会自动根上一行的缩进保持一致 
set smartindent "智能缩进
set ruler "在状态栏显示光标当前位置，哪一行哪一列
set undofile
noremap E 5j "向下移动5行
noremap U 5k "向上移动5行
 
"按下s取消高亮结果显示,本来按下s删除当前字符并进入插入模式
map s :noh<CR> 
map S :w<CR>
map Q :q<CR>
map R :source $MYVIMRC<CR>
map <F2> :NERDTreeToggle<CR>
filetype indent on "开启文件类型检查，并且载入与该类型对应的缩进规则。如何，如果编辑的是.py文件，Vim就是会找到Python的缩进规则